source "https://rubygems.org"

ruby "~> 3.2"

gem "rails", "~> 7.1"
gem "pg", "~> 1.5"
gem "puma", "~> 6.0"
gem "bcrypt", "~> 3.1"
gem "jwt", "~> 2.7"
gem "rack-cors"
gem 'sqlite3', '~> 2.0', '>= 2.0.2'

group :development, :test do
  gem "rspec-rails", "~> 6.1"
  gem "factory_bot_rails"
  gem "faker"
  gem "debug"
end

group :development do
  gem "rubocop-rails", require: false
end
